#ifndef __STD_FUNC_H
 #define __STD_FUNC_H
double add(double x,double y);
double sub(double x,double y);
double mul(double x,double y);
double fdiv(double x,double y);
double neg(double x);
double inv(double x);
double step(double x);
double sgn(double x);
double absv(double x);
double rect(double x);
double doub(double x);
double quant(double x);
double rep(double x);
double sinc(double x);
double gauss(double x);
double delta(double x);
double atanh(double x);
double asinh(double x);
double acosh(double x);
#endif